# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Kobu interpreter

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
        version: '22.1.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: mvn clean install
    - run: mvn -Pnative -DskipTests package
    - run: mkdir staging ** cp target/kobu staging/kobu-${{ matrix.os }}
    - uses: actions/upload-artifact@v3
      with: 
        name: Package
        path: staging
      
